### ISSUE TITLE
Programatically change color and other attributes?

### ISSUE THREAD

**Issue by iantearle** [k0sukey/alloy.widget.iconicfont#1]

**Comment by k0sukey** [comment]
Of course, alloy.widget.iconicfont have to export the applyProperties.

e.g.
.xml
<Widget id="reorder" icon="icon-reorder" src="be.k0suke.fontawesome"/>

.tss
'#reorder': {
  width: Ti.UI.SIZE, height: Ti.UI.SIZE,
  color: '#fff',
  font: { fontSize: 20 }
}

.js
$.reorder.applyProperties({
  color: '#000',
  font: { fontSize: 30 }
});

**Comment by k0sukey** [comment]
xml tag is off :(

.xml
&lt;Widget id="reorder" icon="icon-reorder" src="be.k0suke.fontawesome"/&gt;
